import Layout from "../components/Layout";
import { Container } from "../components/atoms/Container";

export default function Home() {
  return (
    <Layout>
      <Container variant="center">
        <h1 className="mb-4 text-3xl font-bold">API Documentation</h1>
        <h2 className="mb-4 text-xl font-bold">Routes</h2>
      </Container>

      <Container>
        <section>
          <h3 className="mb-4">
            Oracles Index<code className="block">GET /api/oracles/</code>
          </h3>
          <p>Returns all oracle roll tables and their metadata.</p>
        </section>

        <section>
          <h3 className="mb-4">
            Single Oracle
            <code className="block">GET /api/oracles/[slug]</code>
          </h3>
          <p>
            Returns a single oracle roll table and its metadata, by the oracle
            slug. Oracle slug can be obtained from the orcales index route, or
            by referencing the url of the oracle in the app.
          </p>
          <p>
            Eg. <code>GET api/oracles/action</code> fetches the same oracle data
            presented at <code>/oracles/action</code> in the app.
          </p>
        </section>

        <section>
          <h3 className="mb-4">
            Oracle Result
            <code className="block">GET /api/oracles/[slug]/[value]</code>
          </h3>
          <p>
            Returns a single oracle table result and corresponding roll, by the
            table index. Index value can be determined by referencing{" "}
            <code>oracle.results</code> from the orcale metadata, or by
            referencing &quot;runic charts&quot; in the app and subtracting 1
            from those values.
          </p>
          <p>
            Eg. <code>GET api/oracles/action/0</code> returns{" "}
            <code>{'{"roll":1,"result":"Scheme"}'}</code>
          </p>
        </section>

        <section>
          <h3 className="mb-4">
            Oracle Roll
            <code className="block">GET /api/oracles/[slug]/random</code>
          </h3>
          <p>
            Returns a single oracle table result and corresponding roll, at
            random. Random values are generated by random-js using the
            nativeMath PRNG (ie. based on Math.random()).
          </p>
        </section>
      </Container>
    </Layout>
  );
}
