import Link from 'next/link'
import Layout from '../components/Layout'
import { classNames, styleAnimationDelay } from '../lib/util'
import utilityStyles from '../styles/utility.module.css'
import oracleStyles from '../styles/Oracle.module.css'
import docsStyles from '../styles/Docs.module.css'

export default function Home() {
  return (
    <Layout>
      <main>
        <div className={classNames(utilityStyles.container, utilityStyles.content_center)}>
          <h1 className={oracleStyles.text_xl}>API Documentation</h1>
          <h2 className={oracleStyles.text_l}>Routes</h2>
        </div>

        <div className={classNames(utilityStyles.container, utilityStyles.content_left, docsStyles.content_sections)}>

          <section>
            <h3 className={docsStyles.section_head}>Oracles Index<pre>GET /api/oracles/</pre></h3>
            <p>Returns all oracle roll tables and their metadata.</p>
          </section>

          <section>
            <h3 className={docsStyles.section_head}>Single Oracle<pre>GET /api/oracles/[slug]</pre></h3>
            <p>Returns a single oracle roll table and its metadata, by the oracle slug. Oracle slug can be obtained from the orcales index route, or by referencing the url of the oracle in the app.</p>
            <p>Eg. <pre className={docsStyles.inline_pre}>GET api/oracles/action</pre> fetches the same oracle data presented at <pre className={docsStyles.inline_pre}>/oracles/action</pre> in the app.</p>
          </section>

          <section>
            <h3 className={docsStyles.section_head}>Oracle Result<pre>GET /api/oracles/[slug]/[value]</pre></h3>
            <p>Returns a single oracle table result and corresponding roll, by the table index. Index value can be determined by referencing <pre className={docsStyles.inline_pre}>oracle.results</pre> from the orcale metadata, or by referencing "runic charts" in the app and subtracting 1 from those values.</p>
            <p>Eg. <pre className={docsStyles.inline_pre}>GET api/oracles/action/0</pre> returns <pre className={docsStyles.inline_pre}>{'{"roll":1,"result":"Scheme"}'}</pre></p>
          </section>

          <section>
            <h3 className={docsStyles.section_head}>Oracle Roll<pre>GET /api/oracles/[slug]/random</pre></h3>
            <p>Returns a single oracle table result and corresponding roll, at random. Random values are generated by random-js using the nativeMath PRNG (ie. based on Math.random()).</p>
          </section>

        </div>
      </main>
    </Layout >
  )
}
