import Link from 'next/link'
import Layout from '../components/Layout'
import { classNames, styleAnimationDelay } from '../lib/util'
import utilityStyles from '../styles/utility.module.css'
import oracleStyles from '../styles/Oracle.module.css'
import docsStyles from '../styles/Docs.module.css'

export default function Home() {
  return (
    <Layout>
      <main>
        <div className={classNames(utilityStyles.container, utilityStyles.content_center)}>
          <h1 className={oracleStyles.text_xxl}>API Documentation</h1>
          <h2 className={oracleStyles.text_l}>Routes</h2>
        </div>

        <div className={classNames(utilityStyles.container, utilityStyles.content_left, docsStyles.content_sections)}>

          <section>
            <h3 className={docsStyles.section_head}>Oracles Index<code className={docsStyles.header_route}>GET /api/oracles/</code></h3>
            <p>Returns all oracle roll tables and their metadata.</p>
          </section>

          <section>
            <h3 className={docsStyles.section_head}>Single Oracle<code className={docsStyles.header_route}>GET /api/oracles/[slug]</code></h3>
            <p>Returns a single oracle roll table and its metadata, by the oracle slug. Oracle slug can be obtained from the orcales index route, or by referencing the url of the oracle in the app.</p>
            <p>Eg. <code>GET api/oracles/action</code> fetches the same oracle data presented at <code>/oracles/action</code> in the app.</p>
          </section>

          <section>
            <h3 className={docsStyles.section_head}>Oracle Result<code className={docsStyles.header_route}>GET /api/oracles/[slug]/[value]</code></h3>
            <p>Returns a single oracle table result and corresponding roll, by the table index. Index value can be determined by referencing <code>oracle.results</code> from the orcale metadata, or by referencing &quot;runic charts&quot; in the app and subtracting 1 from those values.</p>
            <p>Eg. <code>GET api/oracles/action/0</code> returns <code>{'{"roll":1,"result":"Scheme"}'}</code></p>
          </section>

          <section>
            <h3 className={docsStyles.section_head}>Oracle Roll<code className={docsStyles.header_route}>GET /api/oracles/[slug]/random</code></h3>
            <p>Returns a single oracle table result and corresponding roll, at random. Random values are generated by random-js using the nativeMath PRNG (ie. based on Math.random()).</p>
          </section>

        </div>
      </main>
    </Layout >
  )
}
